# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da55136d45a41e78e21c8ab835a532c47041fac3a32ed3d220e996fb5a13fedd7aebb207a1e10cee5a0e0502111fa7f0efa3a6d699258a47bcf8db4aac77d3ac

test:
  secret_key_base: 1edb4838abc4f11ad29a94cea71706e5fb027c061d5ba3e6846d114af23726d831cac3632ae68daeb99237b63f040f48563d44a7e8485adb91badbabea807db6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
